# Generated by Django 5.1.1 on 2025-07-28 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0002_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
